Fix py2 syntax errors
htm-community/nupic.py pull request #8
Opened 2019-02-25 23:57 UTC by pepedocs

I've worked on top of @ctrl-z-9000-times work, here's what I've done so far.

Fixes:
 - Used `future` to allow py2 compatibility
 - Fixed install errors

With these changes nupic.py can now be installed with latest nupic bindings for both py2 and py3. There are still some test (runtime) errors that are related to py2 compat and also incorrect usage of `nupic.cpp` api.

2019-02-26 09:25 UTC, breznak commented
I'm attaching a nice cheatsheet which basically guides through the py2, 3 compatible rewrite. 
https://python-future.org/compatible_idioms.html

2019-02-26 09:28 UTC, breznak requested changes
Looks good to me! :clap: Thank you, guys! :+1: 

> are still some test (runtime) errors that are related to py2 compat 

please fix these

> and also incorrect usage of nupic.cpp api.

while we'll ignore any of these

Meanwhile, I'll have a look at fixing the CI for this repo.

2019-02-26 10:59 UTC, breznak reviewed
Python 3 will still fail is numenta's bindings do not support it.

2019-02-26 10:59 UTC, breznak commented on requirements.txt
> +#unittest2>=0.5.1
this PR uses `unittest` while PR #5 suggests existing `unittest2` updated to >= 1.10. 
What is the difference?

2019-02-26 11:07 UTC, breznak commented
Only one failing test: 
https://travis-ci.com/htm-community/nupic.py/jobs/180565542#L710

2019-02-26 12:51 UTC, D-McDougall approved these changes
This looks good to me.  Thank you!

2019-02-26 15:26 UTC, breznak approved these changes

2019-02-26 15:27 UTC, breznak commented
I am merging as is, so we can continue the development.

2019-02-26 15:27 UTC, merged

2019-02-27 01:42 UTC, pepedocs commented
> Only one failing test:
> https://travis-ci.com/htm-community/nupic.py/jobs/180565542#L710

I believe this error occurs only for py3? I've got a fix for this, also there are more py2 errors I just have to fix them first.